### ISSUE TITLE
test problems

### ISSUE THREAD

**Issue by SaintLogos1234** [leeyeehoo/SiamRPN-VGG#3]
I trained the model with your tarin code, then I tested it with your VOT code and the following error occurred：
python test_otb.py 
Traceback (most recent call last):
  File "test_otb.py", line 102, in <module>
    main()
  File "test_otb.py", line 91, in main
    net.load_state_dict(torch.load('/home/xieyangyang/Downloads/SiamRPN-VGG-master/VOT/siamrpncheckpoint.pth.tar'))
  File "/home/xieyangyang/anaconda3/envs/Pytorch1/lib/python2.7/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SiamRPNotb:
	Missing key(s) in state_dict: "frontend.0.bias", "frontend.0.weight", "frontend.2.bias", "frontend.2.weight", "frontend.5.bias", "frontend.5.weight", "frontend.7.bias", "frontend.7.weight", "frontend.10.bias", "frontend.10.weight", "frontend.12.bias", "frontend.12.weight", "frontend.14.bias", "frontend.14.weight", "frontend.17.bias", "frontend.17.weight", "frontend.19.bias", "frontend.19.weight", "frontend.21.bias", "frontend.21.weight", "conv_r1.bias", "conv_r1.weight", "conv_r2.bias", "conv_r2.weight", "conv_cls1.bias", "conv_cls1.weight", "conv_cls2.bias", "conv_cls2.weight", "regress_adjust.bias", "regress_adjust.weight". 
	Unexpected key(s) in state_dict: "state_dict", "epoch", "arch", "optimizer", "best_prec1".

**Comment by SaintLogos1234** [comment]
I run vot_SiamRPN.py and the following error occurred:
self._files = [x.strip('\n') for x in open('images.txt', 'r').readlines()]
IOError: [Errno 2] No such file or directory: 'images.txt'
I find I need images.txt, region.txt, However, I am a novice and do not know how to obtain these documents. Can you give me some suggestions? Thank you

**Comment by leeyeehoo** [comment]
I'm not sure which line your error occurs. Can you specify it?
